#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/gregperry/Projects/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/gregperry/Projects/examples/authentication_app"
export "FLUTTER_TARGET=/Users/gregperry/Projects/examples/authentication_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/gregperry/Projects/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.4.1"
export "FLUTTER_BUILD_NUMBER=1.4.1"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
